### ISSUE TITLE
Symbol's value as variable is void: outshine-enforce-no-comment-padding-p

### ISSUE THREAD

**Issue by xuchunyang** [tj64/outorg#14]
I encountered the error with M-x outorg-edit-as-org. outorg was installed from melpa a minute ago.

**Comment by xuchunyang** [comment]
Forgot to mention -- I don't have outshine installed.

**Comment by tj64** [comment]
Hi, no way - outorg depends on outshine, you have to install outshine and structure your files/buffers the outshine (= org-mode) style to be able to use outorg.Have a look at the README's of outshine and outorg.

**Comment by xuchunyang** [comment]
Ok, I see.  If so, you should probably add outshine to the dependencies of this package and load outshine as needed, use e.g.:

    ;; Package-Requires: ((outshine "x.y.z"))
    ...
    (require 'outshine)

**Comment by tj64** [comment]
Outshine requires outorg, that would be a circular dependency and thus introduce an error.
